# Site settings
title: "Levis Agaba"
email: alevis.github.io
description: "My blog"
baseurl: ""
url: "http://alevis.github.io/"
title_description: "My github page."
title_image: "https://avatars1.githubusercontent.com/u/9142438?s=460&v=4"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/alevis/alevis.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: agabalevis
github_username:  alevis
instagram_username: laevs
reddit_username:
linkedin_link: https://www.linkedin.com/in/levis-agaba/
google_plus_link: https://plus.google.com/discover
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/agabalevis\">Levis Agaba</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/alevis/alevis.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
