# Site settings
title: "Agaba Levis"
email: alevis.github.io
description: "Blogging site."
author: "Agaba Levis"
baseurl: ""
url: "http://alevis.github.io/"
title_description: "My blog."
title_image: "https://avatars1.githubusercontent.com/u/9142438?s=460&v=4"
google_analytics: "UA-139204101-1"
disqus_account: alevis-github-io
github_repository: https://github.com/alevis/alevis.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
username: alevis
fullname: levis-agaba
twitter_username: agabalevis
# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/agabalevis\">Levis Agaba</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/alevis/alevis.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
# exclude: [vendor]


