services:
  serene:
    image: ghcr.io/getzola/zola:v0.22.1
    working_dir: /site
    command: serve --interface 0.0.0.0 --port 1111 --drafts --base-url http://localhost
    ports:
      - "1111:1111"
    volumes:
      - ./:/site
